[package]
name = "localhost"
version = "0.1.0"
edition = "2024"

[dependencies]
mio = { version = "0.8", features = ["os-poll", "net"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2.174"
rand = "0.8.5"
